-- AlterTable
ALTER TABLE "User" ADD COLUMN     "blocked" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "emailVerified" DROP NOT NULL,
ALTER COLUMN "image" DROP NOT NULL;
